comments:
    comment_class: App\MainBundle\Document\Comment
    status_default: pending
    template_comments: '@Comments/Default/comments.html.twig'
    template_add_comment_form: '@Comments/Default/add_comment_form.html.twig'
