services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Andchir\CommentsBundle\:
        resource: '../../*'
        exclude: '{DependencyInjection,Form,Document,Resources}'

    comments:
        class: Andchir\CommentsBundle\Service\CommentsManager
        arguments: []
        tags: ['controller.service_arguments']
        public: true
