services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Andchir\CommentsBundle\:
        resource: '../../*'
        exclude: '{}'

    Andchir\CommentsBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

